; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = ATmega328p
framework = arduino

[env:Main]
build_src_filter = +<cdelg045_Main.cpp>

[env:4D7S]
build_src_filter = +<cdelg045_4D7S.cpp>

[env:General]
build_src_filter = +<cdelg045_General.cpp>

[env:4D7S-2]
build_src_filter = +<cdelg045_4D7S-2.cpp>

[env:Screen]
build_src_filter = +<cdelg045_Screen.cpp>

[env:Screen-2]
build_src_filter = +<Game.cpp>